[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869c"
red = "0xea6963"
white = "0xd4be99"
yellow = "0xd8a658"

[colors.primary]
background = "0x282829"
foreground = "0xd4be99"


[cursor]
style = "Beam"
# blinking = on
# blink_interval =  501

[font]
size = 11.5

[font.normal]
family = "mesloLGS NF"
# family = "iosevka"
style = "regular"

[window]
opacity = 1.65

[window.padding]
x = 22
y = 22
